# Generated by Django 5.2.4 on 2026-05-15 10:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='notes/documents/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
