# Generated by Django 5.2.4 on 2026-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_note_document_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('lower', 'Lower Primary'), ('upper', 'Upper Primary'), ('secondary', 'Secondary'), ('early childhood', 'Early Childhood')], max_length=20, unique=True),
        ),
    ]
