# Generated by Django 5.2.4 on 2026-09-03 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('parents', '0003_parentaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reference',
            new_name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='received_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_school_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(default='OLD-INVOICE', editable=False, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('airtel', 'Airtel Money'), ('bank', 'Bank Transfer')], default='airtel', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parents.parent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
