# Generated by Django 5.2.4 on 2026-09-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_payment_fees_amount_payment_lunch_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('airtel', 'Airtel Money'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], max_length=20),
        ),
    ]
