# Generated by Django 5.2.4 on 2026-10-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_issued',
            field=models.BooleanField(default=False),
        ),
    ]
