# Generated by Django 5.2.4 on 2026-03-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='dayx',
        ),
    ]
