# Generated by Django 5.2.4 on 2026-05-11 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_grade_teacher'),
        ('teachers', '0002_remove_attendance_dayx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-year', 'term', 'week']},
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_student_week_day',
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'year', 'term', 'week', 'day'), name='unique_student_attendance'),
        ),
    ]
