# Generated by Django 5.2.4 on 2026-08-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_grade_teacher'),
        ('teachers', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('grade', 'subject', 'test_type', 'term', 'year'), name='unique_test_per_period'),
        ),
    ]
