# Generated by Django 5.2.4 on 2026-08-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_section_name'),
        ('teachers', '0004_test_term_test_year_test_unique_test_per_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='Core.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
