# Generated by Django 5.2.4 on 2026-02-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='last_name',
        ),
    ]
