# Generated by Django 5.2.4 on 2026-09-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_remove_parent_first_name_remove_parent_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_access', models.BooleanField(default=False)),
                ('download_results', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_control', to='parents.parent')),
            ],
        ),
    ]
