# Generated by Django 5.2.4 on 2026-07-29 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0002_note_document_alter_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source_file', models.FileField(upload_to='imports/')),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('generated_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.topic')),
            ],
        ),
    ]
