# Generated by Django 5.2.4 on 2026-07-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('preview', 'Preview'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='end_page',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='start_page',
            field=models.PositiveIntegerField(),
        ),
    ]
